name: CI Build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add nuget sources
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
      run: dotnet nuget add source https://nuget.pkg.github.com/tsmoreland/index.json -n github-tsmoreland -k ${GITHUB_TOKEN}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
